- type: job
  parent: CMSurvivor
  id: RMCEngineerSurvivor
  name: cm-job-name-survivor #make new name
  description: cm-job-description-survivor # Make new description
  playTimeTracker: RMCJobSurvivorEngineer
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMSquad
    time: 18000 # 5 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsEngineering
    time: 18000 # 5 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsMedical
    time: 18000 # 5 hours
  startingGear: RMCGearSurvivorEngineer
  accessGroups:
  - ColonistEngi
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 3
        RMCSkillEngineer: 3
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetEngineer
 
- type: startingGear
  id: RMCGearSurvivorEngineer
  equipment:
    head: ClothingHeadHatBeretEngineering
    eyes: ClothingEyesGlassesMeson
    gloves: CMHandsInsulated
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: CMSatchelEngineer
    shoes: ClothingShoesColorOrange
    id: CMIDCardColonist
    ears: CMHeadsetColony
    pocket1: RMCM5Bayonet
    pocket2: RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: RMCSpawnPointSurvivorEngineer
  name: survivor engineer spawn point
  components:
  - type: SpawnPoint
    job_id: RMCEngineerSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor

- type: playTimeTracker
  id: RMCJobSurvivorEngineer
  isHumanoid: true
